### ISSUE TITLE
Q: What is difference between this repo and maticnetwork/contracts repo?

### ISSUE THREAD

**Issue by sungmin7465** [maticnetwork/pos-portal#103]
genesis contracts in [contracts repo](https://github.com/maticnetwork/contracts)  seem to be deployed on matic's mainnet & testnet.
but, genesis contracts in [pos-portal]([contracts repo](https://github.com/maticnetwork/contracts) ) look better architected & implemented than that. what is the purpose of each of them?

**Comment by itzmeanjan** [comment]
Roughly speaking,

Repo | Purpose
--- | ---
https://github.com/maticnetwork/contracts | Plasma Bridge related smart contracts, along with staking contracts 
https://github.com/maticnetwork/pos-portal | POS Bridge related smart contracts
