### ISSUE TITLE
PREDICATE_ROLE assignment missing in root/RootToken/DummyMintableERC20.sol? Deployment documentation needed.

### ISSUE THREAD

**Issue by VogtAI** [maticnetwork/pos-portal#66]
Is there any documentation for deploying mintable ERC20 on both chains? 

My intuition of the procedure would be the following:
1. Deploy root/RootToken/DummyMintableERC20.sol on Ethereum
2. Deploy child/ChildToken/ChildMintableERC20.sol on Matic
3. Requesting mapping on https://mapper.matic.today/

However how is the rootChainManager supposed to mint tokens if it doesn't have the PREDICATE_ROLE? Shouldn't there be another PREDICATE_ROLE assignment in the constructor or is an additonal external call needed?

**Comment by itzmeanjan** [comment]
Hello @VogtAI 

Taking a look into [this test case](https://github.com/maticnetwork/pos-portal/blob/master/test/predicates/MintableERC20Predicate.test.js) will answer your questions.

**Comment by VogtAI** [comment]
Ok thanks,

so between 2. and 3. I need to run:
`await root.dummyMintableERC20.grantRole(PREDICATE_ROLE, MintableERC20PredicateProxy)`
with MintableERC20PredicateProxy from here https://github.com/maticnetwork/static/blob/master/network/mainnet/v1/index.json

If that's correct then this can be closed.

**Comment by itzmeanjan** [comment]
Yes correct.
